version: 2

models:
  # ============================================================================
  # FINANCE MARTS
  # ============================================================================
  - name: mrr_monthly
    description: |
      Monthly recurring revenue metrics with growth tracking.
      Grain: One row per month.
      Use for MRR trends, customer count, and month-over-month growth analysis.
    columns:
      - name: month
        description: First day of the month (grain)
        tests:
          - unique
          - not_null
      - name: mrr
        description: Monthly recurring revenue (sum of completed transactions)
        tests:
          - not_null
      - name: unique_customers
        description: Count of distinct customers with transactions that month
        tests:
          - not_null
      - name: transaction_count
        description: Total number of transactions in the month
        tests:
          - not_null
      - name: avg_transaction_value
        description: Average transaction amount for the month
        tests:
          - not_null
      - name: arpu
        description: Average revenue per user (mrr / unique_customers)
      - name: growth_rate_pct
        description: Month-over-month growth percentage

    tests:
      - dbt_utils.expression_is_true:
          expression: "mrr >= 0"
          config:
            severity: error
      - dbt_utils.expression_is_true:
          expression: "unique_customers >= 0"
      - dbt_utils.expression_is_true:
          expression: "transaction_count >= 0"
      - dbt_utils.expression_is_true:
          expression: "transaction_count >= unique_customers"
          config:
            where: "unique_customers > 0"

  - name: revenue_summary
    description: |
      Aggregate revenue summary with rolling period comparisons.
      Single row output with total and recent period metrics.
    columns:
      - name: total_revenue
        description: All-time total revenue
        tests:
          - not_null
      - name: total_transactions
        description: All-time transaction count
        tests:
          - not_null
      - name: average_order_value
        description: Total revenue divided by transactions
        tests:
          - not_null
      - name: avg_daily_revenue
        description: Average revenue per day
      - name: first_transaction_date
        description: Date of first recorded transaction
        tests:
          - not_null
      - name: last_transaction_date
        description: Date of most recent transaction
        tests:
          - not_null
      - name: days_with_revenue
        description: Count of days with at least one transaction
        tests:
          - not_null
      - name: revenue_30d
        description: Revenue in the last 30 days
      - name: revenue_7d
        description: Revenue in the last 7 days

    tests:
      - dbt_utils.expression_is_true:
          expression: "total_revenue >= 0"
      - dbt_utils.expression_is_true:
          expression: "total_transactions >= 0"
      - dbt_utils.expression_is_true:
          expression: "average_order_value >= 0"
      - dbt_utils.expression_is_true:
          expression: "first_transaction_date <= last_transaction_date"
      - dbt_utils.expression_is_true:
          expression: "COALESCE(revenue_30d, 0) >= COALESCE(revenue_7d, 0)"

  # ============================================================================
  # MARKETING MARTS
  # ============================================================================
  - name: channel_performance
    description: |
      Marketing channel performance aggregates.
      Grain: One row per channel.
      Key metrics: leads, conversions, spend, revenue, ROAS, CPL, CPA.
    columns:
      - name: channel
        description: Marketing channel name
        tests:
          - unique
          - not_null
      - name: total_leads
        description: Total leads generated by this channel
        tests:
          - not_null
      - name: total_conversions
        description: Total conversions from this channel
        tests:
          - not_null
      - name: conversion_rate
        description: Conversion rate percentage (conversions/leads * 100)
      - name: total_spend
        description: Total marketing spend on this channel
        tests:
          - not_null
      - name: total_revenue
        description: Total revenue attributed to this channel
        tests:
          - not_null
      - name: cost_per_lead
        description: Average cost per lead (spend/leads)
      - name: cost_per_conversion
        description: Average cost per conversion (spend/conversions)
      - name: roas
        description: Return on ad spend (revenue/spend)
      - name: net_revenue
        description: Revenue minus spend
      - name: active_days
        description: Number of days with activity on this channel
        tests:
          - not_null

    tests:
      - dbt_utils.expression_is_true:
          expression: "total_leads >= 0"
      - dbt_utils.expression_is_true:
          expression: "total_conversions >= 0"
      - dbt_utils.expression_is_true:
          expression: "total_conversions <= total_leads"
          config:
            severity: warn
      - dbt_utils.expression_is_true:
          expression: "total_spend >= 0"
      - dbt_utils.expression_is_true:
          expression: "conversion_rate BETWEEN 0 AND 100"
          config:
            where: "conversion_rate IS NOT NULL"

  - name: funnel_conversion
    description: |
      Monthly marketing funnel metrics by channel.
      Grain: One row per month per channel.
      Tracks leads, conversions, spend, and growth trends.
    columns:
      - name: month
        description: First day of the month
        tests:
          - not_null
      - name: channel
        description: Marketing channel
        tests:
          - not_null
      - name: leads
        description: Leads generated that month
        tests:
          - not_null
      - name: conversions
        description: Conversions that month
        tests:
          - not_null
      - name: conversion_rate
        description: Monthly conversion rate percentage
      - name: spend
        description: Marketing spend that month
        tests:
          - not_null
      - name: revenue
        description: Revenue attributed that month
        tests:
          - not_null
      - name: cpl
        description: Cost per lead
      - name: cpa
        description: Cost per acquisition
      - name: leads_growth_pct
        description: Month-over-month leads growth percentage
      - name: conversions_growth_pct
        description: Month-over-month conversions growth percentage

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - month
            - channel
      - dbt_utils.expression_is_true:
          expression: "leads >= 0"
      - dbt_utils.expression_is_true:
          expression: "conversions >= 0"
      - dbt_utils.expression_is_true:
          expression: "conversions <= leads"
          config:
            severity: warn
      - dbt_utils.expression_is_true:
          expression: "spend >= 0"

  # ============================================================================
  # EXPERIMENTS MARTS
  # ============================================================================
  - name: experiment_results
    description: |
      A/B test experiment results with statistical metrics.
      Grain: One row per experiment per variant.
      Includes conversion rates, lift calculations, and revenue metrics.
    columns:
      - name: experiment_name
        description: Name of the experiment
        tests:
          - not_null
      - name: variant
        description: Variant name (control, variant_a, variant_b, etc.)
        tests:
          - not_null
          - accepted_values:
              values: ['control', 'variant_a', 'variant_b', 'variant_c', 'treatment']
              config:
                severity: warn
      - name: is_control
        description: Boolean flag for control group
        tests:
          - not_null
          - accepted_values:
              values: [true, false]
      - name: users
        description: Number of users in this variant
        tests:
          - not_null
      - name: conversions
        description: Number of conversions in this variant
        tests:
          - not_null
      - name: conversion_rate
        description: Conversion rate percentage (4 decimal precision)
      - name: control_conversion_rate
        description: Control group conversion rate for comparison
      - name: absolute_lift
        description: Absolute difference from control conversion rate
      - name: relative_lift_pct
        description: Relative percentage lift from control
      - name: total_revenue
        description: Total revenue from this variant
        tests:
          - not_null
      - name: revenue_per_user
        description: Average revenue per user in variant
      - name: experiment_days
        description: Duration of experiment in days

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - experiment_name
            - variant
      - dbt_utils.expression_is_true:
          expression: "users >= 0"
      - dbt_utils.expression_is_true:
          expression: "conversions >= 0"
      - dbt_utils.expression_is_true:
          expression: "conversions <= users"
      - dbt_utils.expression_is_true:
          expression: "conversion_rate BETWEEN 0 AND 100"
          config:
            where: "conversion_rate IS NOT NULL"
      - dbt_utils.expression_is_true:
          expression: "total_revenue >= 0"
